import { Command } from "@/types/types";

export const help: Command = {
  name: "help",
  description: "Show available commands",
  execute: () => [
    {
      id: Date.now().toString(),
      type: "output",
      content:
        "Shell Features:\n  pipes        cmd1 | cmd2 | cmd3\n  redirection  cmd > file, >> append, < input, 2> stderr, 2>&1\n  operators    cmd1 && cmd2, cmd1 || cmd2, cmd1 ; cmd2\n  variables    echo $HOME, echo ${USER}, echo $?\n  substitution echo $(whoami), files=`ls`\n  braces       echo {a,b,c}, touch file{1..5}.txt\n  globbing     ls *.txt, rm file?.log\n  quoting      echo \"a b\", echo 'literal $x'\n  tilde        cd ~, ls ~/Documents\n  history      !!, !42, !grep\n\nKeyboard:\n  Ctrl+A/E start/end, Ctrl+U/K/W kill, Ctrl+L clear,\n  Ctrl+R reverse-search, Tab completion, Up/Down history\n\nTerminal multiplexer (tmux), prefix = Ctrl+B then:\n  %  split vertically      \"  split horizontally\n  arrows / o  move focus   x  close pane\n  c  new window  n/p next/prev  0-9 select window\n\nAvailable commands:\n\nFile Operations:\n  ls - list directory contents\n  cd - change directory\n  pwd - print working directory\n  mkdir - create directory\n  touch - create file\n  cat - display file content\n  rm - remove files\n  cp - copy files\n  mv - move/rename files\n  find - search for files\n  grep - search text patterns\n  head - display first lines\n  tail - display last lines\n  wc - word, line, character count\n  sort - sort lines\n  uniq - report unique lines\n  cut - extract columns\n  tr - translate characters\n\nSystem Information:\n  ps - show running processes\n  top - display system processes\n  df - disk space usage\n  du - directory space usage\n  free - memory usage\n  uname - system information\n  whoami - current user\n  date - current date/time\n  uptime - system uptime\n  history - command history\n\nFile Permissions:\n  chmod - change file permissions\n  chown - change file ownership\n  chgrp - change group ownership\n\nNetworking:\n  ping - ping a host\n  traceroute - trace route to host\n  wget - download files\n  curl - transfer data\n  netstat - network connections\n  ssh - secure shell (simulated)\n\nText Processing:\n  echo - display text\n  sed - stream editor\n  awk - pattern processing\n  tr - translate characters\n  tee - write stdin to file and stdout\n  xargs - build commands from stdin\n  seq - print number sequences\n  diff - compare files\n\nEditors & Navigation:\n  vim - modal editor (i insert, :wq save & quit)\n  nano - simple editor (^O save, ^X exit)\n  tree - directory tree\n  stat - file status\n  basename / dirname - path helpers\n\nArchive Operations:\n  tar - archive files\n  gzip - compress files\n  gunzip - decompress files\n  zip - create zip archives\n  unzip - extract zip archives\n\nProcess Management:\n  kill - terminate processes\n  jobs - active jobs\n  nohup - run commands immune to hangups\n\nEnvironment:\n  env - environment variables\n  export - set environment variables\n  alias - create command aliases\n\nOther:\n  clear - clear terminal\n  man - manual pages (simulated)\n  which - locate command\n  file - determine file type",
      timestamp: new Date(),
    },
  ],
};
